#!/usr/bin/env python3

import subprocess
from pathlib import Path
from sys import exit
from time import sleep

from loguru import logger as log

log.add(sink=str('/config/logs/poller.log'), level=3, buffering=1, enqueue=True, backtrace=False, diagnose=False, serialize=False, colorize=False, delay=False)

process_path = Path('/poll')
mp4logpath = Path('/config/logs/mp4_automator').mkdir(parents=True, exist_ok=True)


if not process_path.exists():
    log.error('Poll directory does not exist!')
    exit(1)

log.info('Poller is starting...')

while True:
    try:
        skipsleep = False
        for file in process_path.iterdir():
            log.info(f'start of {str(file)}')
            if file.suffix != '.ignored':
                fcontents = file.read_text()
                fsplit = fcontents.split('|')
                if file.suffix == '.deluge':
                    if len(fsplit) < 4:
                        log.warning(f'Cannot parse process file contents ({str(file)})')
                        file.rename(file.with_suffix('.ignored'))
                    else:
                        log.info(f'Processing Deluge download {fsplit[2]}')
                        cmd = ['/opt/mp4_automator/delugePostProcess.py', f'{fsplit[1]}', f'{fsplit[2]}', f'{fsplit[3]}']
                        log.debug(cmd)
                        subprocess.Popen(cmd).wait()
                        file.unlink()
                        skipsleep = True
                elif file.suffix == '.sonarr':
                    log.info(f'Processing Sonarr postprocess')
                    cmd = ['/opt/mp4_automator/postSonarr.py']
                    log.debug(cmd)
                    subprocess.Popen(cmd).wait()
                    file.unlink()
                    skipsleep = True
                elif file.suffix == '.radarr':
                    log.info(f'Processing Radarr postprocess')
                    cmd = ['/opt/mp4_automator/postRadarr.py']
                    log.debug(cmd)
                    subprocess.Popen(cmd).wait()
                    file.unlink()
                log.info(f'Finished Processing of {str(file)}')
    except:
        log.exception('Error in poller script:')
        exit(1)
    if not skipsleep:
        sleep(60)
