#!/usr/bin/env python3

import os
import subprocess
from configparser import ConfigParser
from pathlib import Path
from sys import exit
from time import sleep

from deluge_client import DelugeRPCClient
from loguru import logger as log

__name__ = 'POSTPROC'

os.setgid(int(os.environ['PGID']))
os.setuid(int(os.environ['PUID']))

configfile = "/config/PostProcess.conf"
config = ConfigParser()
config.read(configfile)

loglevel = config.get("general", "loglevel")
logpath = Path(config.get("general", "logpath"))
process_path = Path(config.get("general", "pollpath"))
mp4logpath = Path(config.get("general", "mp4logpath")).mkdir(parents=True, exist_ok=True)
deluge_host = config.get("deluge", "host")
deluge_port = int(config.get("deluge", "port"))
deluge_username = config.get("deluge", "username")
deluge_password = config.get("deluge", "password")

if loglevel == "TRACE":
    lev = 5
elif loglevel == "DEBUG":
    lev = 10
elif loglevel == "INFO":
    lev = 20
elif loglevel == "WARNING":
    lev = 30
else:
    lev = 40

logformat = "{time:YYYY-MM-DD HH:mm:ss.SSS}|{level: <7}|{name}|{message: <72}"

log.add(sink=str(logpath), level=lev, buffering=1, enqueue=True, backtrace=True, diagnose=True, serialize=False, colorize=False, delay=False, format=logformat)

comskip_error = ('Success', 'Did not modify original', 'Sanity Check Failed', 'Exception Handled', 'Failed')

if not process_path.exists():
    log.error('Poll directory does not exist!')
    exit(1)

log.info('Postprocess is starting')

client = DelugeRPCClient(deluge_host, deluge_port, deluge_username, deluge_password)
client.connect()
if client.connected:
    log.debug('Connected to deluge server')
else:
    log.error('Cannot connect to deluge server!')

while True:
    try:
        dvrlist = []
        delugelist = []
        for filep in process_path.iterdir():
            if filep.suffix == '.tvdvr':
                dvrlist.append(filep)
            elif filep.suffix == '.deluge':
                delugelist.append(filep)

        if len(dvrlist) > 0:
            file = dvrlist[0]
            fcontents = file.read_text()
            if fcontents is None:
                log.warning(f'Cannot parse process file contents ({str(file)})')
                file.rename(file.with_suffix('.ignored'))
            else:
                procfull = Path(fcontents.strip())
                procfile = procfull.name
                log.info(f'* Starting TVDVR file to process: {str(procfile)}')
                log.debug(f'Process full filepath: {str(procfull)}')
                log.debug(f'Process File: {str(procfile)}')
                procpath = procfull.parent
                log.debug(f'Process File Path: {str(procpath)}')
                log.info(f'Starting commercial skip detection for: {str(procfile)}')
                cmd = ['/opt/PlexComskip.py', f'{str(procfull)}']
                log.debug(f'cmd: {cmd}')
                process = subprocess.Popen(cmd)
                result = process.wait()
                if result != 0 and result != 2 and result != 1 and result != 4:
                    log.error(f'Error ({comskip_error[result]}) returned from comskip')
                    file.rename(file.with_suffix('.failed'))
                else:
                    log.success(f'Comskip finished ({comskip_error[result]})')
                    configfile = '/config/autoProcessDVR.ini'
                    log.debug(f'Using conversion config file: {configfile}')
                    log.info(f'Starting mp4 conversion for: {str(procfile)}')
                    cmd = ['/usr/bin/python3', '/opt/mp4_automator/manual.py', '-i', f'{procfull}', '-a', '-c', f'{configfile}']
                    log.debug(f'cmd: {cmd}')
                    process = subprocess.Popen(cmd)
                    result = process.wait()
                    if result == 0:
                        log.success(f'Conversion returned success')
                        file.unlink()
                    else:
                        log.error(f'Error ({result}) returned in conversion')
                        file.rename(file.with_suffix('.failed'))
                    log.info(f'* Finished TVDVR file proccessing: {str(procfile)}')

        elif len(delugelist) > 0:
            file = delugelist[0]
            fcontents = file.read_text()
            fsplit = fcontents.split('|')
            if len(fsplit) < 4:
                log.warning(f'Cannot parse process file contents ({str(file)})')
                file.rename(file.with_suffix('.ignored'))
            else:
                procfile = Path(fsplit[2])
                log.info(f'* Starting DELUGE file to process: {str(procfile)}')
                log.debug(f'Process File: {str(procfile)}')
                procpath = Path(fsplit[3])
                log.debug(f'Process File Path: {str(procpath)}')
                downloadid = fsplit[1]
                log.debug(f'Deluge Download ID: {downloadid}')
                procfull = procpath / procfile
                log.debug(f'Process full filepath: {str(procfull)}')
                if str(procpath) == '/downloads/complete/tv':
                    configfile = '/config/autoProcessTV.ini'
                elif str(procpath) == '/downloads/complete/movies':
                    configfile = '/config/autoProcessMOVIE.ini'
                log.debug(f'Using conversion config file: {configfile}')
                log.info(f'Starting mp4 conversion for: {str(procfile)}')
                cmd = ['/usr/bin/python3', '/opt/mp4_automator/manual.py', '-i', f'{procfull}', '-a', '-c', f'{configfile}']
                log.debug(cmd)
                process = subprocess.Popen(cmd)
                result = process.wait()
                if result == 0:
                    log.success(f'Conversion returned success')
                    file.unlink()
                    try:
                        client.call('core.remove_torrent', downloadid, True)
                    except:
                        log.exception(f'Deluge removal for {str(procfile)} failed!')
                    else:
                        log.success(f'Deluge removal for {str(procfile)} success')
                    torrentfile = Path('/downloads/torrents') / (str(procfile) + '.torrent')
                    log.debug(f'Removing torrent file: {str(torrentfile)}')
                    torrentfile.unlink()
                else:
                    log.error(f'Error ({result}) returned in conversion')
                    file.rename(file.with_suffix('.failed'))
                log.info(f'* Finished DELUGE file proccessing: {str(procfile)}')
        else:
            sleep(30)
    except:
        log.exception('Error in postrocess main routine:')
        exit(1)
